run_a: a
	./a
a: a.o 
	cc a.o -o a
a.o: a.c
	cc -c a.c -o a.o
b: b.o 
	cc b.o -o b
b.o: b.c
	cc -c b.c -o b.o
c: c.o 
	cc c.o -o c
c.o: c.c
	cc -c c.c -o c.o
d: d.o 
	cc d.o -o d
d.o: d.c
	cc -c d.c -o d.o
e: e.o 
	cc e.o -o e
e.o: e.c
	cc -c e.c -o e.o